### ISSUE TITLE
The CETL_NODISCARD should be moved to cetl.hpp and then attribute.hpp should be removed

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/CETL#114]
The CETL_NODISCARD should be moved to cetl.hpp and then attribute.hpp should be removed

_Originally posted by @thirtytwobits in https://github.com/OpenCyphal/CETL/pull/113#discussion_r1556499149_

**Comment by serges147** [comment]
Fixed by https://github.com/OpenCyphal/CETL/pull/122 - closing this issue.
