### ISSUE TITLE
Modify `.github/workflows/cetlvast.yml` to accept (in addition to `main`) also `issue/*` branches.

### ISSUE THREAD

**Issue by serges147** [OpenCyphal/CETL#99]
The idea is to have for relatively big features/issues a "stable" buildable staging branch - where multiple consecutive the feature/issue-related PRs could be targeted - before the final merge to the `main` when everything is done - something similar to the git flow process. It's desirable that such `issue/*` branches will be automatically built by our git hub actions.

There is also proposition to establish minimal convention for such branch names, like:`issue/NN_LABEL`, where
- `NN` is github issue number
- `LABEL` very minimal human friendly string giving context of the issue, like f.e. `issue/83_any`.

**Comment by thirtytwobits** [comment]
Yeah +1. Like this idea.
